on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.5
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export

# Left
      - name: West Build (Microdox Left)
        run: west build -s zmk/app -b sparkfun_nrf52840_mini -- -DSHIELD=microdox_mod_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Microdox DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/sparkfun_nrf52840_mini.dts.pre.tmp
      - name: Microdox Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 microdox_mod_left_sparkfun_nrf52840_mini.uf2
      - name: Archive (Microdox Left)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: microdox_mod_left_sparkfun_nrf52840_mini.uf2

# Right
      - name: West Build (Microdox Right)
        run: west build --pristine -s zmk/app -b sparkfun_nrf52840_mini -- -DSHIELD=microdox_mod_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Microdox Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 microdox_mod_right_sparkfun_nrf52840_mini.uf2
      - name: Archive (Microdox Right)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: microdox_mod_right_sparkfun_nrf52840_mini.uf2


# Reset
      - name: purge
        run: rm -rf build
      - name: West Build (sparkfun nrf52840 mini BLE reset)
        run: west build --pristine -s zmk/app -b sparkfun_nrf52840_mini -- -DSHIELD=settings_reset -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 sparkfun_nrf52840_mini_settings_reset.uf2
      - name: Archive (sparkfun_nrf52840_mini settings_reset)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: sparkfun_nrf52840_mini_settings_reset.uf2
